#!/usr/bin/env ruby

require "bundler/setup"
require "micro_cisc"
require "byebug"

if ARGV.length < 1
  puts "Usage:"
  puts "  ucisc <file_name> [<file_name> ...]"
  exit(0)
end

file_names = ARGV.reject { |name| name.start_with?("-") }
puts "Reading #{file_names.join(" ")}"
compiler = MicroCisc.load(file_names)

instructions = compiler.command_count
size = compiler.serialize.size
puts "Running program with #{instructions} instructions compiled to #{size} words"

begin
  MicroCisc.run(compiler.serialize)
rescue StandardError => e
  puts "Execution terminated: #{e.message}"
  puts "  #{e.backtrace.join("\n  ")}"
end

puts "Done."
